const usersData = [
  {
    id: 0,
    name: "John Doe",
    aqi: "9",
    area: "Quận 1",
    status: "Active",
  },
  {
    id: 1,
    name: "Samppa Nori",
    aqi: "9",
    area: "Quận 2",
    status: "Active",
  },
  {
    id: 2,
    name: "Estavan Lykos",
    aqi: "114",
    area: "Quận 3",
    status: "Inactive",
  },
  {
    id: 3,
    name: "Chetan Mohamed",
    aqi: "114",
    area: "Thủ Đức",
    status: "Inactive",
  },
  {
    id: 4,
    name: "Derick Maximinus",
    aqi: "153",
    area: "Quận 2",
    status: "Active",
  },
  {
    id: 5,
    name: "Friderik Dávid",
    aqi: "153",
    area: "Quận 3",
    status: "Active",
  },
  {
    id: 6,
    name: "Yiorgos Avraamu",
    aqi: "9",
    area: "Quận 2",
    status: "Active",
  },
  {
    id: 7,
    name: "Avram Tarasios",
    aqi: "114",
    area: "Quận 3",
    status: "Inactive",
  },
  {
    id: 8,
    name: "Quintin Ed",
    aqi: "114",
    area: "Thủ Đức",
    status: "Inactive",
  },
  {
    id: 9,
    name: "Enéas Kwadwo",
    aqi: "153",
    area: "Quận 2",
    status: "Active",
  },
  {
    id: 10,
    name: "Agapetus Tadeáš",
    aqi: "153",
    area: "Quận 3",
    status: "Active",
  },
  {
    id: 11,
    name: "Carwyn Fachtna",
    aqi: "9",
    area: "Quận 2",
    status: "Active",
  },
  {
    id: 12,
    name: "Nehemiah Tatius",
    aqi: "114",
    area: "Quận 3",
    status: "Inactive",
  },
  {
    id: 13,
    name: "Ebbe Gemariah",
    aqi: "114",
    area: "Thủ Đức",
    status: "Inactive",
  },
  {
    id: 14,
    name: "Eustorgios Amulius",
    aqi: "153",
    area: "Quận 2",
    status: "Active",
  },
  {
    id: 15,
    name: "Leopold Gáspár",
    aqi: "153",
    area: "Quận 3",
    status: "Active",
  },
  {
    id: 16,
    name: "Pompeius René",
    aqi: "9",
    area: "Quận 2",
    status: "Active",
  },
  {
    id: 17,
    name: "Paĉjo Jadon",
    aqi: "114",
    area: "Quận 3",
    status: "Inactive",
  },
  {
    id: 18,
    name: "Micheal Mercurius",
    aqi: "114",
    area: "Thủ Đức",
    status: "Inactive",
  },
  {
    id: 19,
    name: "Ganesha Dubhghall",
    aqi: "153",
    area: "Quận 2",
    status: "Active",
  },
  {
    id: 20,
    name: "Hiroto Šimun",
    aqi: "153",
    area: "Quận 3",
    status: "Active",
  },
  {
    id: 21,
    name: "Vishnu Serghei",
    aqi: "9",
    area: "Quận 2",
    status: "Active",
  },
  {
    id: 22,
    name: "Zbyněk Phoibos",
    aqi: "114",
    area: "Quận 3",
    status: "Inactive",
  },
  {
    id: 23,
    name: "Aulus Agmundr",
    aqi: "9",
    area: "Quận 2",
    status: "Active",
  },
  {
    id: 24,
    name: "Aulus Agmundr",
    aqi: "9",
    area: "Quận 2",
    status: "Active",
  },
];

export default usersData;
